spring:
  application:
    name: consultas-api

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: false

  flyway:
    enabled=false:

  server:
    port: 8080

