spring:
  application:
    name: pagamento

  datasource:
    url: jdbc:postgresql://localhost:5432/loja_spring_boot
    username: postgres
    password: admin123456
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  flyway:
    enabled=false:

  server:
    port: 8080
    error:
      include-stacktrace: never


  web:
    error:
      include-stacktrace: never
